language: java
jdk:
  - openjdk8

# Travis CI 어느 브랜치에서 실행될지 결정
branches:
 only:
   - master

# Travis CI 서버의 Home
# Gradle을 통해 의존성을 받게 되면 이를 Travis CI 디렉토리에 cache하여 다음 배포 때부턴 받지 않도록 설정
cache:
 directories:
   - '$HOME/.m2/repository'
   - '$HOME/.gradle'

# gradlew에 대한 실행 권한 부여
before_install:
 - chmod +x gradlew

# 브랜치 push 되었을 시 수행하는 명령어
script: "./gradlew clean build"

# Travis CI 실행 완료 후 자동 알림 설정
notifications:
  email:
    recipients:
      pranne1224@gmail.com
